In [2]:
# importing libraries

import pandas as pd
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen

In [3]:
url = Request('https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_GDP')
soup = urlopen(url).read()
parse = BeautifulSoup(soup)

In [4]:
# creating DataFrame
df = pd.DataFrame(columns=['Rank', 'State', '2019', '%', 'GDP per Capita', 'Region'])

In [5]:
import re
def number(number):
    return re.sub('[^\w\s.]', '', number)

### Parsing Headers

In [6]:
# parse.find_all('div', attrs={'div':'wikitable sortable jquery-tablesorter'})

tables = parse.find_all('table', attrs={'class':'wikitable sortable'})

In [75]:
ranks = []
countries = []
Q3 = []
perc = []
gdp = []
region = []

for table in tables:
    rows = table.find_all('tr')
    
    for row in rows:
        cells = row.find_all('td')
        
        if len(cells) > 1:
                    rank = cells[0]
                    ranks.append(rank.text)

                    states = cells[1]
                    countries.append(states.text.strip())
                    
                    q = cells[2]
                    Q3.append(number(q.text.strip()))
                    
                    per = cells[3]
                    perc.append(per.text.strip())
                    
                    gdp_1 = cells[4]
                    gdp.append(number(gdp_1.text.strip()))
                    
                    reg_1 = cells[5]
                    region.append(reg_1.text.strip())

In [8]:
# ranks
# countries
# Q3
# perc
# gdp
# region

In [76]:
# how to add data into DataFrame
df = pd.DataFrame({'Rank':ranks, 'State':countries, '2019':Q3, '%':perc, 'GDP per Capita':gdp, 'Region':region})

In [77]:
df.drop('Rank', axis=1, inplace=True)

In [114]:
df['%'].replace('\W\w\W', '', regex=True, inplace=True)

In [ ]:
df['GDP per Capita'].replace('', '', regex=True)

In [84]:
df['2019'] = df['2019'].astype('float')

In [118]:
df

                       State        2019       % GDP per Capita     Region
0      United States[note 2]  21542540.0  100.00          66255
1                 California   3155224.0    14.6          79764       West
2                      Texas   1896063.0     8.8          66061      South
3                   New York   1740745.0     8.1          89076  Northeast
4                    Florida   1100721.0     5.1          51679      South
5                   Illinois    901572.0     4.2          70761    Midwest
6               Pennsylvania    817216.0     3.8          63810  Northeast
7                       Ohio    701438.0     3.3          60006    Midwest
8                 New Jersey    648984.0     3.0          72850  Northeast
9                    Georgia    619818.0     2.9          58921      South
10                Washington    603772.0     2.8          80123       West
11             Massachusetts    599092.0     2.8          86798  Northeast
12            North Carolina    590711.0     2.7          56889      South
13                  Virginia    557144.0     2.6          65410      South
14                  Michigan    543977.0     2.5          54420    Midwest
15                  Maryland    430388.0     2.0          71224      South
16                  Colorado    392348.0     1.8          68887       West
17                 Minnesota    383094.0     1.8          68273    Midwest
18                 Tennessee    382275.0     1.8          56466      South
19                   Indiana    379133.0     1.8          56656    Midwest
20                   Arizona    368556.0     1.7          51391       West
21                 Wisconsin    348822.0     1.6          60001    Midwest
22                  Missouri    334286.0     1.6          54564    Midwest
23               Connecticut    287560.0     1.3          80489  Northeast
24                 Louisiana    264853.0     1.2          56836      South
25                    Oregon    253036.0     1.2          60380       West
26            South Carolina    247711.0     1.1          48722      South
27                   Alabama    232145.0     1.1          47494      South
28                  Kentucky    215586.0     1.0          48247      South
29                  Oklahoma    206254.0     1.0          52308      South
30                      Iowa    195858.0     0.9          62056    Midwest
31                      Utah    189809.0     0.9          60045       West
32                    Nevada    178622.0     0.8          58866       West
33                    Kansas    174183.0     0.8          59826    Midwest
34      District of Columbia    146996.0     0.7         209260      South
35                  Arkansas    134022.0     0.6          44469      South
36                  Nebraska    127941.0     0.6          66316    Midwest
37               Mississippi    119497.0     0.6          40012      South
38                New Mexico    104349.0     0.5          49798       West
39               Puerto Rico    101131.0    0.48          31651   South[D]
40                    Hawaii     97664.0     0.5          68754       West
41             New Hampshire     89152.0     0.4          65724  Northeast
42                     Idaho     81493.0     0.4          46456       West
43             West Virginia     78270.0     0.4          43343      South
44                  Delaware     75765.0     0.4          78337      South
45                     Maine     67905.0     0.3          50736  Northeast
46              Rhode Island     63903.0     0.3          60439  Northeast
47              North Dakota     57106.0     0.3          75132    Midwest
48                    Alaska     55430.0     0.3          75166       West
49              South Dakota     53692.0     0.3          60859    Midwest
50                   Montana     52470.0     0.2          49393       West
51                   Wyoming     39610.0     0.2          68561       West
52                   Vermont     34973.0     0.2          55841  Northeast
53                      Guam      5859.0    0.03          35665    West[C]
54       U.S. Virgin Islands      3855.0    0.02          36802   South[D]
55  Northern Mariana Islands      1593.0   0.007          28164    West[C]
56            American Samoa       634.0   0.003          11399    West[C]

In [74]:
df['2019'] = df['2019'].astype('str')

In [110]:
df['%']

0     100.00[]
1         14.6
2          8.8
3          8.1
4          5.1
5          4.2
6          3.8
7          3.3
8          3.0
9          2.9
10         2.8
11         2.8
12         2.7
13         2.6
14         2.5
15         2.0
16         1.8
17         1.8
18         1.8
19         1.8
20         1.7
21         1.6
22         1.6
23         1.3
24         1.2
25         1.2
26         1.1
27         1.1
28         1.0
29         1.0
30         0.9
31         0.9
32         0.8
33         0.8
34         0.7
35         0.6
36         0.6
37         0.6
38         0.5
39     0.48[A]
40         0.5
41         0.4
42         0.4
43         0.4
44         0.4
45         0.3
46         0.3
47         0.3
48         0.3
49         0.3
50         0.2
51         0.2
52         0.2
53     0.03[A]
54     0.02[A]
55    0.007[A]
56    0.003[A]
Name: %, dtype: object