In [240]:
# importing libraries

import pandas as pd
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen

In [241]:
url = Request('https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_GDP')
soup = urlopen(url).read()
parse = BeautifulSoup(soup)

In [242]:
# creating DataFrame
df = pd.DataFrame(columns=['Rank', 'State', '2019', '%', 'GDP per Capita', 'Region'])

In [404]:
import re
def number(number):
    return re.sub('[^\w\s.]', '', number)

### Parsing Headers

In [399]:
# parse.find_all('div', attrs={'div':'wikitable sortable jquery-tablesorter'})

tables = parse.find_all('table', attrs={'class':'wikitable sortable'})

In [413]:
ranks = []
countries = []
Q3 = []
perc = []
gdp = []
region = []

for table in tables:
    rows = table.find_all('tr')
    
    for row in rows:
        cells = row.find_all('td')
        
        if len(cells) > 1:
                    rank = cells[0]
                    ranks.append(rank.text)

                    states = cells[1]
                    countries.append(states.text.strip())
                    
                    q = cells[2]
                    Q3.append(number(q.text.strip()))
                    
                    per = cells[3]
                    perc.append(per.text.strip())
                    
                    gdp_1 = cells[4]
                    gdp.append(number(gdp_1.text.strip()))
                    
                    reg_1 = cells[5]
                    region.append(reg_1.text.strip())

In [ ]:
# ranks
# countries
# Q3
# perc
# gdp
# region

In [420]:
# how to add data into DataFrame
df = pd.DataFrame({'Rank':ranks, 'State':countries, '2019':Q3, '%':perc, 'GDP per Capita':gdp, 'Region':region})

In [421]:
df

,Rank,State,2019,%,GDP per Capita,Region
0,â€”,United States[note 2],21542540B,100.00[B],66255,
1,1,California,3155224,14.6,79764,West
2,2,Texas,1896063,8.8,66061,South
3,3,New York,1740745,8.1,89076,Northeast
4,4,Florida,1100721,5.1,51679,South
5,5,Illinois,901572,4.2,70761,Midwest
6,6,Pennsylvania,817216,3.8,63810,Northeast
7,7,Ohio,701438,3.3,60006,Midwest
8,8,New Jersey,648984,3.0,72850,Northeast
9,9,Georgia,619818,2.9,58921,South
10,10,Washington,603772,2.8,80123,West
11,11,Massachusetts,599092,2.8,86798,Northeast
12,12,North Carolina,590711,2.7,56889,South
13,13,Virginia,557144,2.6,65410,South
14,14,Michigan,543977,2.5,54420,Midwest
15,15,Maryland,430388,2.0,71224,South
16,16,Colorado,392348,1.8,68887,West
17,17,Minnesota,383094,1.8,68273,Midwest
18,18,Tennessee,382275,1.8,56466,South
19,19,Indiana,379133,1.8,56656,Midwest
20,20,Arizona,368556,1.7,51391,West
21,21,Wisconsin,348822,1.6,60001,Midwest
22,22,Missouri,334286,1.6,54564,Midwest
23,23,Connecticut,287560,1.3,80489,Northeast
24,24,Louisiana,264853,1.2,56836,South
25,25,Oregon,253036,1.2,60380,West
26,26,South Carolina,247711,1.1,48722,South
27,27,Alabama,232145,1.1,47494,South
28,28,Kentucky,215586,1.0,48247,South
29,29,Oklahoma,206254,1.0,52308,South
30,30,Iowa,195858,0.9,62056,Midwest
31,31,Utah,189809,0.9,60045,West
32,32,Nevada,178622,0.8,58866,West
33,33,Kansas,174183,0.8,59826,Midwest
34,34,District of Columbia,146996,0.7,209260,South
35,35,Arkansas,134022,0.6,44469,South
36,36,Nebraska,127941,0.6,66316,Midwest
37,37,Mississippi,119497,0.6,40012,South
38,38,New Mexico,104349,0.5,49798,West
39,39,Puerto Rico,101131,0.48[A],31651,South[D]
40,40,Hawaii,97664,0.5,68754,West
41,41,New Hampshire,89152,0.4,65724,Northeast
42,42,Idaho,81493,0.4,46456,West
43,43,West Virginia,78270,0.4,43343,South
44,44,Delaware,75765,0.4,78337,South
45,45,Maine,67905,0.3,50736,Northeast
46,46,Rhode Island,63903,0.3,60439,Northeast
47,47,North Dakota,57106,0.3,75132,Midwest
48,48,Alaska,55430,0.3,75166,West
49,49,South Dakota,53692,0.3,60859,Midwest
50,50,Montana,52470,0.2,49393,West
51,51,Wyoming,39610,0.2,68561,West
52,52,Vermont,34973,0.2,55841,Northeast
53,53,Guam,5859,0.03[A],35665,West[C]
54,54,U.S. Virgin Islands,3855,0.02[A],36802,South[D]
55,55,Northern Mariana Islands,1593,0.007[A],28164,West[C]
56,56,American Samoa,634,0.003[A],11399,West[C]